@startuml "statelfow"
!include /home/tangpei/sysmgr/UML/style/core.puml
autonumber
Adas->Sysmgr:Registe
hnote over Sysmgr:Normal
Sysmgr->MCU:Sned State Normal

group Clibration
MCU->MCU:Check Sysmgr state
MCU->Sysmgr:Request Normal
Sysmgr->Adas:Send Request to Adas
Adas->Sysmgr:Calibration confirm
hnote over Sysmgr:Calibration
Sysmgr->MCU:Send State Clibration
Adas->Adas:Do Calibration
Adas->Sysmgr:Send Calibration Result
hnote over Sysmgr:Calibration_Finish
Sysmgr->MCU:Send State Calibration_Finish\nwith Restult
end
Adas->Adas:Restart
Adas->Sysmgr:Registe
hnote over Sysmgr:Normal
Sysmgr->MCU:Sned State Normal
@enduml