# Copyright (C) Horizon Robotics, Inc. - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential

 g++ hiredis.cpp -o test -I/home/pei.tang/.local/include/ -L/home/pei.tang/.local/lib -lhiredis